// <auto-generated />
namespace Rest_Rvw5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Unknownchngs2AcctCtrlrAcctVwMdl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unknownchngs2AcctCtrlrAcctVwMdl));
        
        string IMigrationMetadata.Id
        {
            get { return "201802120648528_Unknown-chngs-2-AcctCtrlr-AcctVwMdl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
