// <auto-generated />
namespace Rest_Rvw5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MoveReviewsComments2User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoveReviewsComments2User));
        
        string IMigrationMetadata.Id
        {
            get { return "201802110042469_Move-Reviews-Comments-2-User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
