// <auto-generated />
namespace Rest_Rvw5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingUserFields2code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingUserFields2code));
        
        string IMigrationMetadata.Id
        {
            get { return "201802120436400_Adding-User-Fields-2-code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
